# Generated by Django 4.2.4 on 2023-08-22 14:37

from django.db import migrations, models
import django.db.models.deletion
import gestione.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('moto', models.BooleanField()),
                ('marca', models.CharField(max_length=20)),
                ('modello', models.CharField(max_length=35)),
                ('prezzo', models.PositiveIntegerField()),
                ('data_fabbricazione', models.DateField()),
                ('kilometraggio', models.PositiveIntegerField()),
                ('colore', models.CharField(max_length=15)),
                ('num_proprietari', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Mezzi',
            },
        ),
        migrations.CreateModel(
            name='Venditore',
            fields=[
                ('cf', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('iban', models.CharField(max_length=34)),
                ('telefono', models.CharField(max_length=16)),
                ('pec', models.CharField(max_length=40, null=True)),
                ('mail', models.CharField(max_length=319)),
                ('indirizzo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Venditori',
            },
        ),
        migrations.CreateModel(
            name='ImmaginiMacchina',
            fields=[
                ('car_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestione.mezzo')),
                ('fronte', models.ImageField(upload_to=gestione.models.ImmaginiMacchina.uploadTo)),
                ('retro', models.ImageField(upload_to=gestione.models.ImmaginiMacchina.uploadTo)),
                ('interni', models.ImageField(upload_to=gestione.models.ImmaginiMacchina.uploadTo)),
            ],
            options={
                'verbose_name_plural': 'ImmaginiMacchine',
            },
        ),
        migrations.AddField(
            model_name='mezzo',
            name='venditore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestione.venditore'),
        ),
    ]
