# Generated by Django 4.2.4 on 2023-08-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='venditore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.venditore'),
        ),
    ]
