# Generated by Django 4.2.4 on 2023-08-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_alter_mezzo_venditore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_moto', models.BooleanField()),
                ('marca', models.CharField(max_length=20)),
                ('descrizione', models.TextField(max_length=500)),
                ('prezzo', models.PositiveIntegerField()),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.venditore')),
            ],
            options={
                'verbose_name_plural': 'Accessori',
            },
        ),
    ]
