# Generated by Django 4.2.4 on 2023-08-23 19:33

from django.db import migrations, models
import django.db.models.deletion
import gestione.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0005_alter_immaginimacchina_interni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmaginiAccessorio',
            fields=[
                ('acc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestione.accessorio')),
                ('foto1', models.ImageField(upload_to=gestione.models.ImmaginiAccessorio.uploadTo)),
                ('foto2', models.ImageField(blank=True, null=True, upload_to=gestione.models.ImmaginiAccessorio.uploadTo)),
                ('foto3', models.ImageField(blank=True, null=True, upload_to=gestione.models.ImmaginiAccessorio.uploadTo)),
            ],
            options={
                'verbose_name_plural': 'ImmaginiAccessori',
            },
        ),
    ]
