# Generated by Django 4.2.4 on 2023-08-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_immaginiaccessorio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immaginiaccessorio',
            options={'verbose_name_plural': 'Immagini Accessori'},
        ),
        migrations.AlterModelOptions(
            name='immaginimacchina',
            options={'verbose_name_plural': 'Immagini Macchine'},
        ),
    ]
