# Generated by Django 4.2.4 on 2023-08-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0007_alter_immaginiaccessorio_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessorio',
            old_name='marca',
            new_name='nome',
        ),
    ]
