# Generated by Django 4.2.4 on 2023-08-26 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestione', '0011_favouritemezzo_favouriteaccessorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venditore',
            name='venditore',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
