# Generated by Django 4.2.4 on 2023-08-30 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestione', '0013_oggettocart_carrello'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spedizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.TextField()),
                ('citta', models.CharField(max_length=50)),
                ('CAP', models.CharField(max_length=20)),
                ('stato', models.CharField(max_length=50)),
                ('is_appuntamento', models.BooleanField()),
                ('dataora', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Spedizioni',
            },
        ),
    ]
