# Generated by Django 4.2.4 on 2023-08-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0014_spedizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='spedizione',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
