# Generated by Django 4.2.4 on 2023-08-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0015_spedizione_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spedizione',
            name='dataora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
